export type EmailControlCategory =
  | 'Anti-Phishing'
  | 'Anti-Malware'
  | 'Anti-Spam'
  | 'Safe Links'
  | 'Safe Attachments'
  | 'Authentication'
  | 'Authorization'
  | 'Protocols'
  | 'Mail Flow'
  | 'Data Loss Prevention'
  | 'Encryption'
  | 'Audit'
  | 'Permissions & RBAC'
  | 'Informational';

export interface EmailControlScoringRule {
  controlId: string;
  severity: 'critical' | 'high' | 'medium' | 'low' | 'informational';
  weight: number;
  category: EmailControlCategory;
  passScore: number;
  failScore: number;
  partialScore: number;
}

export const EMAIL_CONTROL_SCORING_RULES: Record<string, EmailControlScoringRule> = {
  'email-ap-01': {
    controlId: 'email-ap-01',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-02': {
    controlId: 'email-ap-02',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-03': {
    controlId: 'email-ap-03',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-04': {
    controlId: 'email-ap-04',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-05': {
    controlId: 'email-ap-05',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-06': {
    controlId: 'email-ap-06',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-07': {
    controlId: 'email-ap-07',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-08': {
    controlId: 'email-ap-08',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-09': {
    controlId: 'email-ap-09',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-ap-10': {
    controlId: 'email-ap-10',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Phishing',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-am-01': {
    controlId: 'email-am-01',
    severity: 'critical',
    weight: 2.5,
    category: 'Anti-Malware',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-am-02': {
    controlId: 'email-am-02',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Malware',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-am-03': {
    controlId: 'email-am-03',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Malware',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-am-04': {
    controlId: 'email-am-04',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Malware',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-am-05': {
    controlId: 'email-am-05',
    severity: 'high',
    weight: 2.0,
    category: 'Anti-Malware',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-01': {
    controlId: 'email-as-01',
    severity: 'high',
    weight: 1.5,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-02': {
    controlId: 'email-as-02',
    severity: 'high',
    weight: 1.5,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-03': {
    controlId: 'email-as-03',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-04': {
    controlId: 'email-as-04',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-05': {
    controlId: 'email-as-05',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-06': {
    controlId: 'email-as-06',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-07': {
    controlId: 'email-as-07',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-08': {
    controlId: 'email-as-08',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-09': {
    controlId: 'email-as-09',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-10': {
    controlId: 'email-as-10',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-11': {
    controlId: 'email-as-11',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-12': {
    controlId: 'email-as-12',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-13': {
    controlId: 'email-as-13',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-14': {
    controlId: 'email-as-14',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-15': {
    controlId: 'email-as-15',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-16': {
    controlId: 'email-as-16',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-17': {
    controlId: 'email-as-17',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-18': {
    controlId: 'email-as-18',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-as-19': {
    controlId: 'email-as-19',
    severity: 'medium',
    weight: 1.0,
    category: 'Anti-Spam',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-sl-01': {
    controlId: 'email-sl-01',
    severity: 'high',
    weight: 1.5,
    category: 'Safe Links',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-sl-02': {
    controlId: 'email-sl-02',
    severity: 'high',
    weight: 1.5,
    category: 'Safe Links',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-sa-01': {
    controlId: 'email-sa-01',
    severity: 'high',
    weight: 1.5,
    category: 'Safe Attachments',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-sa-02': {
    controlId: 'email-sa-02',
    severity: 'high',
    weight: 1.5,
    category: 'Safe Attachments',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-auth-01': {
    controlId: 'email-auth-01',
    severity: 'high',
    weight: 1.5,
    category: 'Authentication',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-auth-02': {
    controlId: 'email-auth-02',
    severity: 'high',
    weight: 1.5,
    category: 'Authentication',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-auth-03': {
    controlId: 'email-auth-03',
    severity: 'medium',
    weight: 1.0,
    category: 'Authentication',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-dlp-01': {
    controlId: 'email-dlp-01',
    severity: 'high',
    weight: 1.5,
    category: 'Data Loss Prevention',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-dlp-02': {
    controlId: 'email-dlp-02',
    severity: 'medium',
    weight: 1.0,
    category: 'Data Loss Prevention',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-enc-01': {
    controlId: 'email-enc-01',
    severity: 'medium',
    weight: 1.0,
    category: 'Encryption',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-enc-02': {
    controlId: 'email-enc-02',
    severity: 'medium',
    weight: 1.0,
    category: 'Encryption',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-audit-01': {
    controlId: 'email-audit-01',
    severity: 'medium',
    weight: 1.0,
    category: 'Audit',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-audit-02': {
    controlId: 'email-audit-02',
    severity: 'medium',
    weight: 1.0,
    category: 'Audit',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-rbac-01': {
    controlId: 'email-rbac-01',
    severity: 'high',
    weight: 1.5,
    category: 'Permissions & RBAC',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-rbac-02': {
    controlId: 'email-rbac-02',
    severity: 'high',
    weight: 1.5,
    category: 'Permissions & RBAC',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-rbac-03': {
    controlId: 'email-rbac-03',
    severity: 'critical',
    weight: 2.5,
    category: 'Permissions & RBAC',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-smtp-01': {
    controlId: 'email-smtp-01',
    severity: 'high',
    weight: 1.5,
    category: 'Authentication',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-pop-01': {
    controlId: 'email-pop-01',
    severity: 'medium',
    weight: 1.0,
    category: 'Protocols',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-conn-01': {
    controlId: 'email-conn-01',
    severity: 'medium',
    weight: 1.0,
    category: 'Mail Flow',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-conn-02': {
    controlId: 'email-conn-02',
    severity: 'medium',
    weight: 1.0,
    category: 'Mail Flow',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-tr-01': {
    controlId: 'email-tr-01',
    severity: 'medium',
    weight: 1.0,
    category: 'Mail Flow',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-tr-02': {
    controlId: 'email-tr-02',
    severity: 'medium',
    weight: 1.0,
    category: 'Data Loss Prevention',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-tr-03': {
    controlId: 'email-tr-03',
    severity: 'low',
    weight: 0.5,
    category: 'Mail Flow',
    passScore: 100,
    failScore: 0,
    partialScore: 50,
  },
  'email-cm-01': {
    controlId: 'email-cm-01',
    severity: 'informational',
    weight: 0,
    category: 'Informational',
    passScore: 100,
    failScore: 0,
    partialScore: 0,
  },
  'email-cm-02': {
    controlId: 'email-cm-02',
    severity: 'informational',
    weight: 0,
    category: 'Informational',
    passScore: 100,
    failScore: 0,
    partialScore: 0,
  },
  'email-cm-03': {
    controlId: 'email-cm-03',
    severity: 'informational',
    weight: 0,
    category: 'Informational',
    passScore: 100,
    failScore: 0,
    partialScore: 0,
  },
  'email-cm-09': {
    controlId: 'email-cm-09',
    severity: 'informational',
    weight: 0,
    category: 'Informational',
    passScore: 100,
    failScore: 0,
    partialScore: 0,
  },
  'email-cm-11': {
    controlId: 'email-cm-11',
    severity: 'informational',
    weight: 0,
    category: 'Informational',
    passScore: 100,
    failScore: 0,
    partialScore: 0,
  },
};

export const EMAIL_CATEGORY_WEIGHTS: Record<EmailControlCategory, number> = {
  'Anti-Phishing': 3.0,
  'Anti-Malware': 3.0,
  'Anti-Spam': 2.0,
  'Safe Links': 2.0,
  'Safe Attachments': 2.0,
  'Authentication': 2.5,
  'Authorization': 2.0,
  'Protocols': 1.0,
  'Mail Flow': 1.5,
  'Data Loss Prevention': 1.5,
  'Encryption': 1.0,
  'Audit': 1.0,
  'Permissions & RBAC': 2.5,
  'Informational': 0,
};

export function getEmailControlRule(controlId: string): EmailControlScoringRule | undefined {
  return EMAIL_CONTROL_SCORING_RULES[controlId];
}

export function getEmailCategoryWeight(category: EmailControlCategory): number {
  return EMAIL_CATEGORY_WEIGHTS[category] || 1;
}
