import { query } from '../db/connection';

export interface ReportData {
  assessment: any;
  modules: any[];
  findings: any[];
  metadata: Record<string, string>;
  organization: {
    name: string;
    tenantName?: string;
  };
  detailedRequest?: {
    manualReviewNotes: string | null;
    assessorSignature: string | null;
    assessorSignOffDate: string | null;
    supportingDocs: any[];
  };
}

export async function generatePDFReport(assessmentId: string): Promise<Buffer> {
  // In production, use PDFKit or Puppeteer to generate actual PDF
  // For now, return a placeholder buffer
  const reportData = await getReportData(assessmentId);
  
  // Placeholder PDF content
  const pdfContent = `
VELOCYVERSE SECURITY ASSESSMENT REPORT
=====================================

Assessment ID: ${reportData.assessment.id}
Type: ${reportData.assessment.type}
Status: ${reportData.assessment.status}
Overall Score: ${reportData.assessment.overallScore || 0}/100
Score Band: ${reportData.assessment.scoreBand || 'N/A'}

Organization: ${reportData.organization.name}
Tenant: ${reportData.organization.tenantName || 'N/A'}

Completed: ${reportData.assessment.completedAt ? new Date(reportData.assessment.completedAt).toLocaleString() : 'N/A'}

MODULE SCORES
-------------
${Object.entries(reportData.metadata).map(([key, value]) => `${key}: ${value}`).join('\n')}

FINDINGS SUMMARY
----------------
Total Findings: ${reportData.findings.length}
Passed: ${reportData.findings.filter((f: any) => f.result === 'pass').length}
Failed: ${reportData.findings.filter((f: any) => f.result === 'fail').length}
Not Applicable: ${reportData.findings.filter((f: any) => f.result === 'not_applicable').length}

TOP FINDINGS
------------
${reportData.findings.filter((f: any) => f.result === 'fail').slice(0, 10).map((f: any, i: number) => `${i + 1}. ${f.control_name} (${f.severity})`).join('\n')}

---
Generated by Aegis Security Assessment Platform
  `;

  return Buffer.from(pdfContent, 'utf-8');
}

export async function generateExcelReport(assessmentId: string): Promise<Buffer> {
  // In production, use ExcelJS to generate actual Excel file
  // For now, return a placeholder buffer
  const reportData = await getReportData(assessmentId);
  
  // Simple CSV format as placeholder
  let csv = 'Module,Control,Result,Severity,Evidence,Recommendation\n';
  
  for (const finding of reportData.findings) {
    const f = finding as any;
    csv += `"${f.module_name}","${f.control_name}","${f.result}","${f.severity}","${f.evidence}","${f.recommendation}"\n`;
  }

  return Buffer.from(csv, 'utf-8');
}

async function getReportData(assessmentId: string): Promise<ReportData> {
  const assessment = await query('SELECT * FROM assessments WHERE id = ?', [assessmentId]);
  const modules = await query('SELECT * FROM assessment_modules WHERE assessment_id = ?', [assessmentId]);
  const findings = await query(
    `SELECT f.*, cc.control_name, cc.module_name, cc.severity
     FROM findings f
     JOIN control_catalog cc ON f.control_catalog_id = cc.id
     WHERE f.assessment_module_id IN (SELECT id FROM assessment_modules WHERE assessment_id = ?)`,
    [assessmentId]
  );
  const metadata = await query('SELECT * FROM assessment_metadata WHERE assessment_id = ?', [assessmentId]);
  
  const metaMap: Record<string, string> = {};
  (metadata as any[]).forEach((m: any) => {
    metaMap[m.key] = m.value;
  });

  // Get organization info
  const orgResult = await query(
    'SELECT o.name, tc.tenant_name FROM organizations o JOIN assessments a ON a.organization_id = o.id LEFT JOIN tenant_connections tc ON a.tenant_connection_id = tc.id WHERE a.id = ?',
    [assessmentId]
  );

  // Get detailed assessment request data (for appendix)
  let detailedRequest;
  const detailedRequests = await query(
    'SELECT * FROM detailed_assessment_requests WHERE assessment_id = ?',
    [assessmentId]
  );
  if (detailedRequests.length > 0) {
    const dr = detailedRequests[0] as any;
    detailedRequest = {
      manualReviewNotes: dr.manual_review_notes || null,
      assessorSignature: dr.assessor_signature || null,
      assessorSignOffDate: dr.assessor_sign_off_date || null,
      supportingDocs: dr.supporting_docs ? JSON.parse(dr.supporting_docs) : [],
    };
  }

  return {
    assessment: assessment[0],
    modules: modules as any[],
    findings: findings as any[],
    metadata: metaMap,
    organization: {
      name: (orgResult[0] as any)?.name || 'Unknown',
      tenantName: (orgResult[0] as any)?.tenant_name,
    },
    detailedRequest,
  };
}
